import type { Metadata } from "next";

import { geist, geist_Mono } from "@/config/fonts";

import "./globals.css";


export const metadata: Metadata = {
  title: {
    template: '%s | Fenix Shop',
    default: 'Fenix Shop',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geist_Mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
