import type { Metadata } from "next";


import "./globals.css";
import { Provider } from "@/components";
import { fontMono } from "@/config/fonts";



export const metadata: Metadata = {
  title: {
    template: '%s | Fenix Shop',
    default: 'Fenix Shop',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMono.variable} ${fontMono.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
